### ISSUE TITLE
Bug: 'req.json({code}) is not a function' error

### ISSUE THREAD

**Issue by ScorpIan555** [ScorpIan555/garage-resale#7]
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node node_modules/vertex360/www/vertex_server.js`
listening on 3000...
	GET / 200 25.108 ms - 1224
GET /css/themify-icons.css 200 6.866 ms - 16454
GET /dist/bundle/commons.js 200 7.641 ms - 5815
GET /dist/css/style.min.css 200 7.661 ms - 249341
GET /dist/js/vendor.min.js 200 7.816 ms - 184725
GET /dist/bundle/app.js 200 7.838 ms - 2372255
GET /dist/bundle/commons.map 200 1.334 ms - 5904
GET /fonts/themify.woff?-fvbane 200 1.806 ms - 56108
GET /dist/bundle/app.map 200 1.431 ms - 2494311
GET /auth/currentuser 500 2.894 ms - 1930
TypeError: req.json is not a function
    at /Users/ian/work/garage-resale/routes/auth.js:30:9
    at Layer.handle [as handle_request] (/Users/ian/work/garage-resale/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ian/work/garage-resale/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/ian/work/garage-resale/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ian/work/garage-resale/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/ian/work/garage-resale/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:317:13)
    at /Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:275:10)
    at /Users/ian/work/garage-resale/node_modules/express/lib/router/index.js:635:15
GET /api/item 200 320.870 ms - 4104
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

**Comment by ScorpIan555** [comment]
Fixed this, routes/auth.js said req.json instead of res.json for the response
